### ISSUE TITLE
Functions.php: Enqueue Scripts Organization

### ISSUE THREAD

**Issue by rcass** [redacademy/hummingbird-fall-2017#14]
There is just a renegade enqueue scripts call at the bottom of functions.php 🤔 

This one... I have no idea why it is just hanging out all by its lonesome at the bottom of functions.php:
```
wp_enqueue_script( 'wpb_togglemenu', get_template_directory_uri() . '/js/navigation.js', array('jquery'), '20160909', true );
}
```

Best to add this with the rest of enqueued scripts and styles for organization sake (and that it won't really work unless inside a function, that gets called).

**Comment by ghost** [comment]
Resolved.
