### ISSUE TITLE
Header.php: Remove link and Enqueue Google Fonts

### ISSUE THREAD

**Issue by rcass** [redacademy/hummingbird-fall-2017#16]
In header.php there is a link tag to the google fonts. 

Wordpress works a little different in regards to adding scripts and styles, remember it is all through enqueuing! So remove this link and enqueue in functions.php.

[Here](http://www.wpexplorer.com/google-fonts-wordpress/) is more info (just dont follow the plugin steps because you dont need that)! And we also have some previous wordpress slides on this.

**Comment by ghost** [comment]
Completed!
