### ISSUE TITLE
Make logo and name link to the homepage

### ISSUE THREAD

**Issue by rcass** [redacademy/hummingbird-fall-2017#3]
![screen shot 2017-12-14 at 3 27 20 pm](https://user-images.githubusercontent.com/5028555/34019355-565e2d98-e0e3-11e7-8181-806daf2964ca.png)

**Comment by Lateworm** [comment]
This was completed this morning on the develop branch, but needs to be merged and deployed still.

**Comment by rcass** [comment]
Awesome, I see these changes have been deployed to staging 👍
