### ISSUE TITLE
404 page Add left/right margin to text

### ISSUE THREAD

**Issue by rcass** [redacademy/hummingbird-fall-2017#4]
so it doesn't go right against the viewport

**Comment by rcass** [comment]
I would add a more. This is current:
![screen shot 2017-12-15 at 10 57 40 am](https://user-images.githubusercontent.com/5028555/34056205-e8140d22-e186-11e7-9cf7-1ffcc00dca51.png)

Maybe move to something like this:
![screen shot 2017-12-15 at 11 01 57 am](https://user-images.githubusercontent.com/5028555/34056340-6c8411b0-e187-11e7-926a-77c851e7e2ba.png)

**Comment by ghost** [comment]
We've made the changes but we'll dploy at the end of the day!

**Comment by rcass** [comment]
Okay, well just close this when it is 100% resolved then 👍  (aka the change is added to master and deployed and can be verified)

**Comment by ghost** [comment]
Done!
