### ISSUE TITLE
Functionality Plugin: Necessary?

### ISSUE THREAD

**Issue by rcass** [redacademy/hummingbird-fall-2017#7]
I noticed there are no custom post types or custom taxonomies?
The biggest thing I can see the plugin doing is removing editor links.

Is there anything else that this plugin is doing?

If not, seems like a bit of overkill. I would just move that remove editor link into the theme under inc/extras.php.

**Comment by Lateworm** [comment]
I don't see code to remove editor links. I don't see it in the functionality plugin or the extras.php. @NCMoseley @hamdyfarah13 have one of you already dealt with this?

**Comment by rcass** [comment]
I noticed the functionality plugin is still there. What is the reasoning for keeping it?

The function I was referring to is this:
https://github.com/redacademy/hummingbird-fall-2017/blob/edac7f1345cb73af004539d8b7bc157667eb5e03/plugins/hummingbird-functionality/lib/functions/general.php#L107

**Comment by Lateworm** [comment]
Functionality is now moved and plugin deleted.

**Comment by rcass** [comment]
woot 👍
